# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uart.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuart.proto\x12\nuart_proto\"K\n\nUartConfig\x12*\n\nperipheral\x18\x01 \x01(\x0e\x32\x16.uart_proto.Peripheral\x12\x11\n\tbaud_rate\x18\x02 \x01(\r\":\n\x0cUartTransmit\x12*\n\nperipheral\x18\x01 \x01(\x0e\x32\x16.uart_proto.Peripheral\"9\n\x0bUartReceive\x12*\n\nperipheral\x18\x01 \x01(\x0e\x32\x16.uart_proto.Peripheral*\"\n\nPeripheral\x12\t\n\x05UART1\x10\x00\x12\t\n\x05UART2\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uart_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PERIPHERAL']._serialized_start=222
  _globals['_PERIPHERAL']._serialized_end=256
  _globals['_UARTCONFIG']._serialized_start=26
  _globals['_UARTCONFIG']._serialized_end=101
  _globals['_UARTTRANSMIT']._serialized_start=103
  _globals['_UARTTRANSMIT']._serialized_end=161
  _globals['_UARTRECEIVE']._serialized_start=163
  _globals['_UARTRECEIVE']._serialized_end=220
# @@protoc_insertion_point(module_scope)
