/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "dac.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(dac_proto_DacConfigRequest, dac_proto_DacConfigRequest, AUTO)


PB_BIND(dac_proto_DacConfigStatus, dac_proto_DacConfigStatus, AUTO)


PB_BIND(dac_proto_DacDataRequest, dac_proto_DacDataRequest, 2)


PB_BIND(dac_proto_DacDataStatus, dac_proto_DacDataStatus, AUTO)


PB_BIND(dac_proto_DacNotification, dac_proto_DacNotification, AUTO)


PB_BIND(dac_proto_DacMsg, dac_proto_DacMsg, 2)






