/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_GPIO_PROTO_GPIO_PB_H_INCLUDED
#define PB_GPIO_PROTO_GPIO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _gpio_proto_MsgType {
    gpio_proto_MsgType_CONFIG = 0,
    gpio_proto_MsgType_DATA = 1
} gpio_proto_MsgType;

typedef enum _gpio_proto_GpioMode {
    gpio_proto_GpioMode_INPUT_PULLDOWN = 0,
    gpio_proto_GpioMode_INPUT_PULLUP = 1,
    gpio_proto_GpioMode_INPUT_NOPULL = 2,
    gpio_proto_GpioMode_OUTPUT_PUSHPULL = 3,
    gpio_proto_GpioMode_OUTPUT_OPENDRAIN = 4
} gpio_proto_GpioMode;

/* Struct definitions */
typedef struct _gpio_proto_GpioConfig {
    gpio_proto_GpioMode gpio1;
    gpio_proto_GpioMode gpio2;
    gpio_proto_GpioMode gpio3;
    gpio_proto_GpioMode gpio4;
} gpio_proto_GpioConfig;

typedef struct _gpio_proto_GpioData {
    bool gpio1;
    bool gpio2;
    bool gpio3;
    bool gpio4;
} gpio_proto_GpioData;

typedef struct _gpio_proto_GpioMsg {
    uint32_t sequence_number;
    pb_size_t which_msg;
    union {
        gpio_proto_GpioConfig cfg_msg;
        gpio_proto_GpioData data_msg;
    } msg;
} gpio_proto_GpioMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _gpio_proto_MsgType_MIN gpio_proto_MsgType_CONFIG
#define _gpio_proto_MsgType_MAX gpio_proto_MsgType_DATA
#define _gpio_proto_MsgType_ARRAYSIZE ((gpio_proto_MsgType)(gpio_proto_MsgType_DATA+1))

#define _gpio_proto_GpioMode_MIN gpio_proto_GpioMode_INPUT_PULLDOWN
#define _gpio_proto_GpioMode_MAX gpio_proto_GpioMode_OUTPUT_OPENDRAIN
#define _gpio_proto_GpioMode_ARRAYSIZE ((gpio_proto_GpioMode)(gpio_proto_GpioMode_OUTPUT_OPENDRAIN+1))

#define gpio_proto_GpioConfig_gpio1_ENUMTYPE gpio_proto_GpioMode
#define gpio_proto_GpioConfig_gpio2_ENUMTYPE gpio_proto_GpioMode
#define gpio_proto_GpioConfig_gpio3_ENUMTYPE gpio_proto_GpioMode
#define gpio_proto_GpioConfig_gpio4_ENUMTYPE gpio_proto_GpioMode




/* Initializer values for message structs */
#define gpio_proto_GpioConfig_init_default       {_gpio_proto_GpioMode_MIN, _gpio_proto_GpioMode_MIN, _gpio_proto_GpioMode_MIN, _gpio_proto_GpioMode_MIN}
#define gpio_proto_GpioData_init_default         {0, 0, 0, 0}
#define gpio_proto_GpioMsg_init_default          {0, 0, {gpio_proto_GpioConfig_init_default}}
#define gpio_proto_GpioConfig_init_zero          {_gpio_proto_GpioMode_MIN, _gpio_proto_GpioMode_MIN, _gpio_proto_GpioMode_MIN, _gpio_proto_GpioMode_MIN}
#define gpio_proto_GpioData_init_zero            {0, 0, 0, 0}
#define gpio_proto_GpioMsg_init_zero             {0, 0, {gpio_proto_GpioConfig_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define gpio_proto_GpioConfig_gpio1_tag          1
#define gpio_proto_GpioConfig_gpio2_tag          2
#define gpio_proto_GpioConfig_gpio3_tag          3
#define gpio_proto_GpioConfig_gpio4_tag          4
#define gpio_proto_GpioData_gpio1_tag            1
#define gpio_proto_GpioData_gpio2_tag            2
#define gpio_proto_GpioData_gpio3_tag            3
#define gpio_proto_GpioData_gpio4_tag            4
#define gpio_proto_GpioMsg_sequence_number_tag   1
#define gpio_proto_GpioMsg_cfg_msg_tag           2
#define gpio_proto_GpioMsg_data_msg_tag          3

/* Struct field encoding specification for nanopb */
#define gpio_proto_GpioConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    gpio1,             1) \
X(a, STATIC,   SINGULAR, UENUM,    gpio2,             2) \
X(a, STATIC,   SINGULAR, UENUM,    gpio3,             3) \
X(a, STATIC,   SINGULAR, UENUM,    gpio4,             4)
#define gpio_proto_GpioConfig_CALLBACK NULL
#define gpio_proto_GpioConfig_DEFAULT NULL

#define gpio_proto_GpioData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     gpio1,             1) \
X(a, STATIC,   SINGULAR, BOOL,     gpio2,             2) \
X(a, STATIC,   SINGULAR, BOOL,     gpio3,             3) \
X(a, STATIC,   SINGULAR, BOOL,     gpio4,             4)
#define gpio_proto_GpioData_CALLBACK NULL
#define gpio_proto_GpioData_DEFAULT NULL

#define gpio_proto_GpioMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sequence_number,   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,cfg_msg,msg.cfg_msg),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,data_msg,msg.data_msg),   3)
#define gpio_proto_GpioMsg_CALLBACK NULL
#define gpio_proto_GpioMsg_DEFAULT NULL
#define gpio_proto_GpioMsg_msg_cfg_msg_MSGTYPE gpio_proto_GpioConfig
#define gpio_proto_GpioMsg_msg_data_msg_MSGTYPE gpio_proto_GpioData

extern const pb_msgdesc_t gpio_proto_GpioConfig_msg;
extern const pb_msgdesc_t gpio_proto_GpioData_msg;
extern const pb_msgdesc_t gpio_proto_GpioMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define gpio_proto_GpioConfig_fields &gpio_proto_GpioConfig_msg
#define gpio_proto_GpioData_fields &gpio_proto_GpioData_msg
#define gpio_proto_GpioMsg_fields &gpio_proto_GpioMsg_msg

/* Maximum encoded size of messages (where known) */
#define gpio_proto_GpioConfig_size               8
#define gpio_proto_GpioData_size                 8
#define gpio_proto_GpioMsg_size                  16

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
