/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "gpio.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(gpio_proto_GpioConfig, gpio_proto_GpioConfig, AUTO)


PB_BIND(gpio_proto_GpioData, gpio_proto_GpioData, AUTO)


PB_BIND(gpio_proto_GpioMsg, gpio_proto_GpioMsg, AUTO)





