/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "i2c.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(i2c_proto_I2cConfig, i2c_proto_I2cConfig, AUTO)


PB_BIND(i2c_proto_I2cMasterRequest, i2c_proto_I2cMasterRequest, 2)


PB_BIND(i2c_proto_I2cMasterStatus, i2c_proto_I2cMasterStatus, 2)


PB_BIND(i2c_proto_I2cMsg, i2c_proto_I2cMsg, 2)




