/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "uart.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(uart_proto_UartConfig, uart_proto_UartConfig, AUTO)


PB_BIND(uart_proto_UartData, uart_proto_UartData, 2)


PB_BIND(uart_proto_UartMsg, uart_proto_UartMsg, 2)





